// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {device} from '../models';

export function BackupDevice(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function GetDeviceInfo(arg1:string):Promise<Record<string, string>>;

export function GetDevices():Promise<Array<device.Device>>;

export function RestoreDevice(arg1:string,arg2:string,arg3:string):Promise<void>;
