// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupDevice(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BackupDevice'](arg1, arg2, arg3, arg4);
}

export function GetDeviceInfo(arg1) {
  return window['go']['main']['App']['GetDeviceInfo'](arg1);
}

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function RestoreDevice(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreDevice'](arg1, arg2, arg3);
}
